steps:
- script: node build.js $(TARGET_ARCH)
  displayName: Build

- bash: |
    BRANCH=$(Build.SourceBranch)
    TAG=${BRANCH:10}
    echo "##vso[task.setvariable variable=Name;isOutput=true]$TAG"
  displayName: Get Tag Name
  name: Tag
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

- task: GithubRelease@0
  displayName: Create GitHub Release
  condition: and(succeeded(), startsWith(variables['Tag.Name'], 'v'))
  inputs:
    gitHubConnection: GitHub Yue
    repositoryName: yue/yode
    action: Edit
    tagSource: auto
    tag: $(Tag.Name)
    title: Yode $(Tag.name)
    releaseNotesSource: input
    releaseNotes: (placeholder)
    assets: 'out/Release/*.zip'
    assetUploadMode: replace
    isDraft: true
    addChangelog: false
